In [1]:
import numpy as np

In [2]:
import pandas as pd

In [3]:
data=pd.read_csv("iris.csv")

In [4]:
data.describe()

               Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count  150.000000     150.000000    150.000000     150.000000    150.000000
mean    75.500000       5.843333      3.054000       3.758667      1.198667
std     43.445368       0.828066      0.433594       1.764420      0.763161
min      1.000000       4.300000      2.000000       1.000000      0.100000
25%     38.250000       5.100000      2.800000       1.600000      0.300000
50%     75.500000       5.800000      3.000000       4.350000      1.300000
75%    112.750000       6.400000      3.300000       5.100000      1.800000
max    150.000000       7.900000      4.400000       6.900000      2.500000

In [5]:
data.SepalLengthCm.unique() 
# This returns all unique/distinct values present in the SepalLengthCm column.

array([5.1, 4.9, 4.7, 4.6, 5. , 5.4, 4.4, 4.8, 4.3, 5.8, 5.7, 5.2, 5.5,
       4.5, 5.3, 7. , 6.4, 6.9, 6.5, 6.3, 6.6, 5.9, 6. , 6.1, 5.6, 6.7,
       6.2, 6.8, 7.1, 7.6, 7.3, 7.2, 7.7, 7.4, 7.9])

In [6]:
data.groupby(data.SepalLengthCm).count() 
# This groups the dataset by SepalLengthCm and counts the number of non-null values in each column for every group.

               Id  SepalWidthCm  PetalLengthCm  PetalWidthCm  Species
SepalLengthCm
4.3             1             1              1             1        1
4.4             3             3              3             3        3
4.5             1             1              1             1        1
4.6             4             4              4             4        4
4.7             2             2              2             2        2
4.8             5             5              5             5        5
4.9             6             6              6             6        6
5.0            10            10             10            10       10
5.1             9             9              9             9        9
5.2             4             4              4             4        4
5.3             1             1              1             1        1
5.4             6             6              6             6        6
5.5             7             7              7             7        7
5.6             6             6              6             6        6
5.7             8             8              8             8        8
5.8             7             7              7             7        7
5.9             3             3              3             3        3
6.0             6             6              6             6        6
6.1             6             6              6             6        6
6.2             4             4              4             4        4
6.3             9             9              9             9        9
6.4             7             7              7             7        7
6.5             5             5              5             5        5
6.6             2             2              2             2        2
6.7             8             8              8             8        8
6.8             3             3              3             3        3
6.9             4             4              4             4        4
7.0             1             1              1             1        1
7.1             1             1              1             1        1
7.2             3             3              3             3        3
7.3             1             1              1             1        1
7.4             1             1              1             1        1
7.6             1             1              1             1        1
7.7             4             4              4             4        4
7.9             1             1              1             1        1

In [7]:
data.groupby(data.SepalWidthCm).min() 
# This groups the dataset based on SepalWidthCm values and finds the minimum value of every column within each group.

              Id  SepalLengthCm  PetalLengthCm  PetalWidthCm          Species
SepalWidthCm
2.0           61            5.0            3.5           1.0  Iris-versicolor
2.2           63            6.0            4.0           1.0  Iris-versicolor
2.3           42            4.5            1.3           0.3      Iris-setosa
2.4           58            4.9            3.3           1.0  Iris-versicolor
2.5           70            4.9            3.0           1.1  Iris-versicolor
2.6           80            5.5            3.5           1.0  Iris-versicolor
2.7           60            5.2            3.9           1.0  Iris-versicolor
2.8           55            5.6            4.0           1.2  Iris-versicolor
2.9            9            4.4            1.4           0.2      Iris-setosa
3.0            2            4.3            1.1           0.1      Iris-setosa
3.1            4            4.6            1.5           0.1      Iris-setosa
3.2            3            4.4            1.2           0.2      Iris-setosa
3.3           24            5.0            1.4           0.2      Iris-setosa
3.4            7            4.6            1.4           0.2      Iris-setosa
3.5            1            5.0            1.3           0.2      Iris-setosa
3.6            5            4.6            1.0           0.2      Iris-setosa
3.7           11            5.1            1.5           0.2      Iris-setosa
3.8           19            5.1            1.5           0.2      Iris-setosa
3.9            6            5.4            1.3           0.4      Iris-setosa
4.0           15            5.8            1.2           0.2      Iris-setosa
4.1           33            5.2            1.5           0.1      Iris-setosa
4.2           34            5.5            1.4           0.2      Iris-setosa
4.4           16            5.7            1.5           0.4      Iris-setosa

In [8]:
data.groupby(data.SepalWidthCm).max() 
# This groups the dataset based on SepalWidthCm values and finds the maximum value of every column within each group.

               Id  SepalLengthCm  PetalLengthCm  PetalWidthCm          Species
SepalWidthCm
2.0            61            5.0            3.5           1.0  Iris-versicolor
2.2           120            6.2            5.0           1.5   Iris-virginica
2.3            94            6.3            4.4           1.3  Iris-versicolor
2.4            82            5.5            3.8           1.1  Iris-versicolor
2.5           147            6.7            5.8           2.0   Iris-virginica
2.6           135            7.7            6.9           2.3   Iris-virginica
2.7           143            6.4            5.3           1.9   Iris-virginica
2.8           134            7.7            6.7           2.4   Iris-virginica
2.9           108            7.3            6.3           1.8   Iris-virginica
3.0           150            7.7            6.6           2.3   Iris-virginica
3.1           142            6.9            5.6           2.4   Iris-virginica
3.2           144            7.2            6.0           2.3   Iris-virginica
3.3           145            6.7            6.0           2.5   Iris-virginica
3.4           149            6.3            5.6           2.4   Iris-virginica
3.5            44            5.5            1.6           0.6      Iris-setosa
3.6           110            7.2            6.1           2.5   Iris-virginica
3.7            49            5.4            1.5           0.4      Iris-setosa
3.8           132            7.9            6.7           2.2   Iris-virginica
3.9            17            5.4            1.7           0.4      Iris-setosa
4.0            15            5.8            1.2           0.2      Iris-setosa
4.1            33            5.2            1.5           0.1      Iris-setosa
4.2            34            5.5            1.4           0.2      Iris-setosa
4.4            16            5.7            1.5           0.4      Iris-setosa

In [9]:
data.groupby('SepalLengthCm').mean(numeric_only=True)
# This groups the dataset by SepalLengthCm and calculates the average (mean) of all numeric columns for each group.

                       Id  SepalWidthCm  PetalLengthCm  PetalWidthCm
SepalLengthCm
4.3             14.000000      3.000000       1.100000      0.100000
4.4             30.333333      3.033333       1.333333      0.200000
4.5             42.000000      2.300000       1.300000      0.300000
4.6             20.500000      3.325000       1.325000      0.225000
4.7             16.500000      3.200000       1.450000      0.200000
4.8             25.400000      3.180000       1.580000      0.200000
4.9             41.666667      2.866667       2.283333      0.533333
5.0             39.200000      3.120000       1.840000      0.430000
5.1             35.111111      3.477778       1.722222      0.400000
5.2             37.500000      3.425000       2.075000      0.475000
5.3             49.000000      3.700000       1.500000      0.200000
5.4             28.666667      3.550000       2.033333      0.516667
5.5             67.000000      2.842857       3.228571      0.900000
5.6             84.666667      2.816667       4.200000      1.416667
5.7             72.250000      3.100000       3.587500      1.100000
5.8             88.428571      2.885714       4.071429      1.400000
5.9             94.333333      3.066667       4.700000      1.700000
6.0             95.166667      2.733333       4.650000      1.500000
6.1             94.166667      2.850000       4.750000      1.416667
6.2            110.750000      2.825000       4.750000      1.725000
6.3            107.222222      2.855556       5.133333      1.811111
6.4            107.857143      2.957143       5.157143      1.871429
6.5            107.200000      3.000000       5.240000      1.900000
6.6             67.500000      2.950000       4.500000      1.350000
6.7            112.125000      3.050000       5.262500      1.962500
6.8            111.333333      3.000000       5.400000      1.933333
6.9            114.000000      3.125000       5.275000      2.050000
7.0             51.000000      3.200000       4.700000      1.400000
7.1            103.000000      3.000000       5.900000      2.100000
7.2            122.000000      3.266667       5.966667      1.966667
7.3            108.000000      2.900000       6.300000      1.800000
7.4            131.000000      2.800000       6.100000      1.900000
7.6            106.000000      3.000000       6.600000      2.100000
7.7            124.000000      3.050000       6.600000      2.200000
7.9            132.000000      3.800000       6.400000      2.000000

In [10]:
data.groupby('SepalLengthCm').std(numeric_only=True)
# This groups the dataset by SepalLengthCm and calculates the  Standard Deviation of all numeric columns for each group.

                      Id  SepalWidthCm  PetalLengthCm  PetalWidthCm
SepalLengthCm
4.3                  NaN           NaN            NaN           NaN
4.4            18.583146      0.152753       0.057735      0.000000
4.5                  NaN           NaN            NaN           NaN
4.6            20.141168      0.221736       0.221736      0.050000
4.7            19.091883      0.000000       0.212132      0.000000
4.8            14.046352      0.204939       0.204939      0.070711
4.9            37.866432      0.326599       1.309071      0.671317
5.0            26.029044      0.543241       0.834266      0.326769
5.1            28.117808      0.411636       0.504425      0.282843
5.2            15.154757      0.573730       1.217580      0.618466
5.3                  NaN           NaN            NaN           NaN
5.4            29.001149      0.350714       1.217648      0.491596
5.5            24.779023      0.723089       1.302196      0.489898
5.6            22.060523      0.194079       0.456070      0.312517
5.7            37.821951      0.656832       1.296630      0.545108
5.8            40.265192      0.494734       1.381683      0.728011
5.9            48.418316      0.115470       0.458258      0.173205
6.0            28.435307      0.471876       0.403733      0.268328
6.1            30.413265      0.151658       0.516720      0.204124
6.2            34.798228      0.492443       0.479583      0.434933
6.3            30.780586      0.400347       0.504975      0.407567
6.4            32.328669      0.207020       0.534968      0.368394
6.5            33.558903      0.141421       0.450555      0.264575
6.6            12.020815      0.070711       0.141421      0.070711
6.7            31.984092      0.250713       0.523552      0.420671
6.8            33.531080      0.200000       0.556776      0.472582
6.9            41.753243      0.050000       0.350000      0.378594
7.0                  NaN           NaN            NaN           NaN
7.1                  NaN           NaN            NaN           NaN
7.2            10.583005      0.305505       0.152753      0.472582
7.3                  NaN           NaN            NaN           NaN
7.4                  NaN           NaN            NaN           NaN
7.6                  NaN           NaN            NaN           NaN
7.7             8.286535      0.525991       0.346410      0.141421
7.9                  NaN           NaN            NaN           NaN

In [11]:
data.dtypes

Id                 int64
SepalLengthCm    float64
SepalWidthCm     float64
PetalLengthCm    float64
PetalWidthCm     float64
Species              str
dtype: object

In [12]:
data.groupby(data.SepalWidthCm).describe()

                Id                                                            \
             count        mean        std   min    25%    50%     75%    max
SepalWidthCm
2.0            1.0   61.000000        NaN  61.0  61.00   61.0   61.00   61.0
2.2            3.0   84.000000  31.320920  63.0  66.00   69.0   94.50  120.0
2.3            4.0   69.500000  25.423087  42.0  51.00   71.0   89.50   94.0
2.4            3.0   73.666667  13.576941  58.0  69.50   81.0   81.50   82.0
2.5            8.0  101.125000  24.654397  70.0  85.75  103.0  110.25  147.0
2.6            5.0  103.600000  22.645088  80.0  91.00   93.0  119.00  135.0
2.7            9.0   96.777778  26.630705  60.0  83.00   95.0  112.00  143.0
2.8           14.0  103.428571  30.127203  55.0  74.75  118.5  128.50  134.0
2.9           10.0   75.800000  29.412016   9.0  64.25   77.0   97.75  108.0
3.0           26.0   88.692308  44.418707   2.0  63.25   94.0  125.25  150.0
3.1           12.0   73.750000  53.851859   4.0  34.00   59.5  138.50  142.0
3.2           13.0   73.230769  44.738413   3.0  43.00   52.0  116.00  144.0
3.3            6.0   83.666667  47.276492  24.0  51.75   79.0  119.00  145.0
3.4           12.0   47.750000  49.103092   7.0  18.75   28.0   51.50  149.0
3.5            6.0   28.166667  16.339115   1.0  20.50   32.5   40.00   44.0
3.6            3.0   46.000000  56.151581   5.0  14.00   23.0   66.50  110.0
3.7            3.0   27.333333  19.553346  11.0  16.50   22.0   35.50   49.0
3.8            6.0   63.500000  49.294016  19.0  26.25   46.0  100.25  132.0
3.9            2.0   11.500000   7.778175   6.0   8.75   11.5   14.25   17.0
4.0            1.0   15.000000        NaN  15.0  15.00   15.0   15.00   15.0
4.1            1.0   33.000000        NaN  33.0  33.00   33.0   33.00   33.0
4.2            1.0   34.000000        NaN  34.0  34.00   34.0   34.00   34.0
4.4            1.0   16.000000        NaN  16.0  16.00   16.0   16.00   16.0

             SepalLengthCm            ... PetalLengthCm      PetalWidthCm  \
                     count      mean  ...           75%  max        count
SepalWidthCm                          ...
2.0                    1.0  5.000000  ...         3.500  3.5          1.0
2.2                    3.0  6.066667  ...         4.750  5.0          3.0
2.3                    4.0  5.325000  ...         4.100  4.4          4.0
2.4                    3.0  5.300000  ...         3.750  3.8          3.0
2.5                    8.0  5.762500  ...         5.000  5.8          8.0
2.6                    5.0  6.160000  ...         5.600  6.9          5.0
2.7                    9.0  5.855556  ...         5.100  5.3          9.0
2.8                   14.0  6.335714  ...         5.475  6.7         14.0
2.9                   10.0  6.060000  ...         4.675  6.3         10.0
3.0                   26.0  6.015385  ...         5.425  6.6         26.0
3.1                   12.0  5.941667  ...         5.175  5.6         12.0
3.2                   13.0  5.884615  ...         5.300  6.0         13.0
3.3                    6.0  6.016667  ...         5.700  6.0          6.0
3.4                   12.0  5.316667  ...         2.550  5.6         12.0
3.5                    6.0  5.150000  ...         1.475  1.6          6.0
3.6                    3.0  5.600000  ...         3.750  6.1          3.0
3.7                    3.0  5.266667  ...         1.500  1.5          3.0
3.8                    6.0  6.100000  ...         5.275  6.7          6.0
3.9                    2.0  5.400000  ...         1.600  1.7          2.0
4.0                    1.0  5.800000  ...         1.200  1.2          1.0
4.1                    1.0  5.200000  ...         1.500  1.5          1.0
4.2                    1.0  5.500000  ...         1.400  1.4          1.0
4.4                    1.0  5.700000  ...         1.500  1.5          1.0


                  mean       std  min    25%   50%    75%  max
SepalWidthCm
2.0           1.000000       NaN  1.0  1.000  1.00  1.000  1.0
2.2           1.333333  0.288675  1.0  1.250  1.50  1.500  1.5
2.3           0.975000  0.471699  0.3  0.825  1.15  1.300  1.3
2.4           1.033333  0.057735  1.0  1.000  1.00  1.050  1.1
2.5           1.550000  0.354562  1.1  1.250  1.60  1.825  2.0
2.6           1.420000  0.511859  1.0  1.200  1.20  1.400  2.3
2.7           1.555556  0.343188  1.0  1.300  1.60  1.900  1.9
2.8           1.707143  0.395094  1.2  1.325  1.65  2.000  2.4
2.9           1.320000  0.441714  0.2  1.300  1.30  1.475  1.8
3.0           1.403846  0.744301  0.1  1.225  1.55  1.950  2.3
3.1           1.141667  0.935617  0.1  0.175  1.45  1.875  2.4
3.2           1.261538  0.916095  0.2  0.200  1.50  2.000  2.3
3.3           1.566667  1.003328  0.2  0.775  1.85  2.400  2.5
3.4           0.716667  0.857940  0.2  0.200  0.25  0.700  2.4
3.5           0.300000  0.154919  0.2  0.200  0.25  0.300  0.6
3.6           0.966667  1.327906  0.2  0.200  0.20  1.350  2.5
3.7           0.266667  0.115470  0.2  0.200  0.20  0.300  0.4
3.8           0.900000  0.933809  0.2  0.300  0.35  1.600  2.2
3.9           0.400000  0.000000  0.4  0.400  0.40  0.400  0.4
4.0           0.200000       NaN  0.2  0.200  0.20  0.200  0.2
4.1           0.100000       NaN  0.1  0.100  0.10  0.100  0.1
4.2           0.200000       NaN  0.2  0.200  0.20  0.200  0.2
4.4           0.400000       NaN  0.4  0.400  0.40  0.400  0.4

[23 rows x 32 columns]

In [13]:
data.groupby('SepalLengthCm').std(numeric_only=True)

                      Id  SepalWidthCm  PetalLengthCm  PetalWidthCm
SepalLengthCm
4.3                  NaN           NaN            NaN           NaN
4.4            18.583146      0.152753       0.057735      0.000000
4.5                  NaN           NaN            NaN           NaN
4.6            20.141168      0.221736       0.221736      0.050000
4.7            19.091883      0.000000       0.212132      0.000000
4.8            14.046352      0.204939       0.204939      0.070711
4.9            37.866432      0.326599       1.309071      0.671317
5.0            26.029044      0.543241       0.834266      0.326769
5.1            28.117808      0.411636       0.504425      0.282843
5.2            15.154757      0.573730       1.217580      0.618466
5.3                  NaN           NaN            NaN           NaN
5.4            29.001149      0.350714       1.217648      0.491596
5.5            24.779023      0.723089       1.302196      0.489898
5.6            22.060523      0.194079       0.456070      0.312517
5.7            37.821951      0.656832       1.296630      0.545108
5.8            40.265192      0.494734       1.381683      0.728011
5.9            48.418316      0.115470       0.458258      0.173205
6.0            28.435307      0.471876       0.403733      0.268328
6.1            30.413265      0.151658       0.516720      0.204124
6.2            34.798228      0.492443       0.479583      0.434933
6.3            30.780586      0.400347       0.504975      0.407567
6.4            32.328669      0.207020       0.534968      0.368394
6.5            33.558903      0.141421       0.450555      0.264575
6.6            12.020815      0.070711       0.141421      0.070711
6.7            31.984092      0.250713       0.523552      0.420671
6.8            33.531080      0.200000       0.556776      0.472582
6.9            41.753243      0.050000       0.350000      0.378594
7.0                  NaN           NaN            NaN           NaN
7.1                  NaN           NaN            NaN           NaN
7.2            10.583005      0.305505       0.152753      0.472582
7.3                  NaN           NaN            NaN           NaN
7.4                  NaN           NaN            NaN           NaN
7.6                  NaN           NaN            NaN           NaN
7.7             8.286535      0.525991       0.346410      0.141421
7.9                  NaN           NaN            NaN           NaN

In [14]:
data.Species.unique()

<StringArray>
['Iris-setosa', 'Iris-versicolor', 'Iris-virginica']
Length: 3, dtype: str

In [15]:
data.groupby(data.Species).count()

                 Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
Species
Iris-setosa      50             50            50             50            50
Iris-versicolor  50             50            50             50            50
Iris-virginica   50             50            50             50            50

In [16]:
data.groupby(data.Species).max()

                  Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
Species
Iris-setosa       50            5.8           4.4            1.9           0.6
Iris-versicolor  100            7.0           3.4            5.1           1.8
Iris-virginica   150            7.9           3.8            6.9           2.5

In [17]:
data.groupby(data.Species).mean()

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm
Species,,,,,
Iris-setosa,25.5,5.006,3.418,1.464,0.244
Iris-versicolor,75.5,5.936,2.770,4.260,1.326
Iris-virginica,125.5,6.588,2.974,5.552,2.026

In [18]:
data.groupby(data.Species).std()

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm
Species,,,,,
Iris-setosa,14.57738,0.352490,0.381024,0.173511,0.107210
Iris-versicolor,14.57738,0.516171,0.313798,0.469911,0.197753
Iris-virginica,14.57738,0.635880,0.322497,0.551895,0.274650