In [1]:
# numpy-> Used for Numerical Operations 
# pandas->Data Manipulation and reading datasets
# matplotlib->Used for the Data Visualization
# seaborn->Advanced than matplotlib (for HeatMaps,Pair Plots)
# scikitlearn->Used for Machine learning algorithms

In [2]:
import pandas as pd

In [3]:
import  numpy as np

In [4]:
df=pd.read_csv("iris.csv")
# Reading of the Dataset

In [5]:
print(df)
# printing the dataframe

      Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
0      1            5.1           3.5            1.4           0.2
1      2            4.9           3.0            1.4           0.2
2      3            4.7           3.2            1.3           0.2
3      4            4.6           3.1            1.5           0.2
4      5            5.0           3.6            1.4           0.2
..   ...            ...           ...            ...           ...
145  146            6.7           3.0            5.2           2.3
146  147            6.3           2.5            5.0           1.9
147  148            6.5           3.0            5.2           2.0
148  149            6.2           3.4            5.4           2.3
149  150            5.9           3.0            5.1           1.8

            Species
0       Iris-setosa
1       Iris-setosa
2       Iris-setosa
3       Iris-setosa
4       Iris-setosa
..              ...
145  Iris-virginica
146  Iris-virginica
147  Iris-virginica
148  Iris-virginica
149  Iris-virginica

[150 rows x 6 columns]

In [6]:
print(df.head())
# Printing the rows from top

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [7]:
df.index
# The index (row labels) of the Dataset.

RangeIndex(start=0, stop=150, step=1)

In [8]:
df.columns
# The column labels of the Dataset

Index(['Id', 'SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm', 'PetalWidthCm',
       'Species'],
      dtype='str')

In [9]:
df.shape
# Return a tuple representing the dimensionality of the
# Dataset.

(150, 6)

In [10]:
df.dtypes
# Return the dtypes in the Dataset.

Id                 int64
SepalLengthCm    float64
SepalWidthCm     float64
PetalLengthCm    float64
PetalWidthCm     float64
Species              str
dtype: object

In [11]:
df.columns.values

<StringArray>
[           'Id', 'SepalLengthCm',  'SepalWidthCm', 'PetalLengthCm',
  'PetalWidthCm',       'Species']
Length: 6, dtype: str

In [12]:
df.describe()
# Generate descriptive statistics.

               Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count  150.000000     150.000000    150.000000     150.000000    150.000000
mean    75.500000       5.843333      3.054000       3.758667      1.198667
std     43.445368       0.828066      0.433594       1.764420      0.763161
min      1.000000       4.300000      2.000000       1.000000      0.100000
25%     38.250000       5.100000      2.800000       1.600000      0.300000
50%     75.500000       5.800000      3.000000       4.350000      1.300000
75%    112.750000       6.400000      3.300000       5.100000      1.800000
max    150.000000       7.900000      4.400000       6.900000      2.500000

In [14]:
df['SepalLengthCm']
# Read Data ColumnWise

0      5.1
1      4.9
2      4.7
3      4.6
4      5.0
      ...
145    6.7
146    6.3
147    6.5
148    6.2
149    5.9
Name: SepalLengthCm, Length: 150, dtype: float64

In [15]:
df.sort_values(by='SepalLengthCm')
# Sorting values ColumnWise

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
13,14,4.3,3.0,1.1,0.1,Iris-setosa
8,9,4.4,2.9,1.4,0.2,Iris-setosa
42,43,4.4,3.2,1.3,0.2,Iris-setosa
38,39,4.4,3.0,1.3,0.2,Iris-setosa
41,42,4.5,2.3,1.3,0.3,Iris-setosa
...,...,...,...,...,...,...
122,123,7.7,2.8,6.7,2.0,Iris-virginica
117,118,7.7,3.8,6.7,2.2,Iris-virginica
118,119,7.7,2.6,6.9,2.3,Iris-virginica
135,136,7.7,3.0,6.1,2.3,Iris-virginica
131,132,7.9,3.8,6.4,2.0,Iris-virginica

In [16]:
df.iloc[3]

Id                         4
SepalLengthCm            4.6
SepalWidthCm             3.1
PetalLengthCm            1.5
PetalWidthCm             0.2
Species          Iris-setosa
Name: 3, dtype: object

In [17]:
df.iloc[1:4 , 2:5]
# iloc->Slicing the data

   SepalWidthCm  PetalLengthCm  PetalWidthCm
1           3.0            1.4           0.2
2           3.2            1.3           0.2
3           3.1            1.5           0.2

# checking missing values in the dataset

In [18]:
df.isnull()

        Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  Species
0    False          False         False          False         False    False
1    False          False         False          False         False    False
2    False          False         False          False         False    False
3    False          False         False          False         False    False
4    False          False         False          False         False    False
..     ...            ...           ...            ...           ...      ...
145  False          False         False          False         False    False
146  False          False         False          False         False    False
147  False          False         False          False         False    False
148  False          False         False          False         False    False
149  False          False         False          False         False    False

[150 rows x 6 columns]

In [19]:
df.isnull().sum()

Id               0
SepalLengthCm    0
SepalWidthCm     0
PetalLengthCm    0
PetalWidthCm     0
Species          0
dtype: int64

In [20]:
df.isnull().any()

Id               False
SepalLengthCm    False
SepalWidthCm     False
PetalLengthCm    False
PetalWidthCm     False
Species          False
dtype: bool

In [21]:
df['SepalLengthCm'].isnull().any()

np.False_

In [22]:
df['SepalLengthCm'].isnull().sum()

np.int64(0)

In [23]:
df['PetalLengthCm']=df['PetalLengthCm'].astype("int")

In [24]:
df['PetalLengthCm'].dtype

dtype('int64')

In [25]:
df['PetalLengthCm']=df['PetalLengthCm'].astype('float64')

In [26]:
df['PetalLengthCm'].dtype

dtype('float64')

# data Normalization

In [ ]:
from sklearn import preprocessing
# only uses preprocessing module from sklearn
# Normalization->Mapping all Nominal value into Uniform Scale
    # Method->Min-Max Scaling ->Converts values between range 0 and 1.

    # Nor=X-Xmin/Xmax-Xmin

In [ ]:
x=df[['SepalLengthCm','SepalWidthCm','PetalLengthCm','PetalWidthCm']]
# Selects numerical columns from dataset.

In [ ]:
min_max_scaler=preprocessing.MinMaxScaler()
# Creates Min-Max normalization object.

In [ ]:
x_scaled=min_max_scaler.fit_transform(x)
# values become in range 0 to 1

In [51]:
dataframe=pd.DataFrame(x_scaled)

In [52]:
print(dataframe)
# Need of Normalization ->
# We do normalization because machine learning algorithms perform better when all features are on a similar scale.

            0         1    2         3
0    0.222222  0.625000  0.0  0.041667
1    0.166667  0.416667  0.0  0.041667
2    0.111111  0.500000  0.0  0.041667
3    0.083333  0.458333  0.0  0.041667
4    0.194444  0.666667  0.0  0.041667
..        ...       ...  ...       ...
145  0.666667  0.416667  0.8  0.916667
146  0.555556  0.208333  0.8  0.750000
147  0.611111  0.416667  0.8  0.791667
148  0.527778  0.583333  0.8  0.916667
149  0.444444  0.416667  0.8  0.708333

[150 rows x 4 columns]

In [58]:
label_encoder=preprocessing.LabelEncoder()
# creates label_encoder Object

In [60]:
df = pd.read_csv("Iris.csv")

In [61]:
df['Species']=label_encoder.fit_transform(df['Species'])

In [63]:
print(df['Species'])
print(df)

0      0
1      0
2      0
3      0
4      0
      ..
145    2
146    2
147    2
148    2
149    2
Name: Species, Length: 150, dtype: int64
      Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  Species
0      1            5.1           3.5            1.4           0.2        0
1      2            4.9           3.0            1.4           0.2        0
2      3            4.7           3.2            1.3           0.2        0
3      4            4.6           3.1            1.5           0.2        0
4      5            5.0           3.6            1.4           0.2        0
..   ...            ...           ...            ...           ...      ...
145  146            6.7           3.0            5.2           2.3        2
146  147            6.3           2.5            5.0           1.9        2
147  148            6.5           3.0            5.2           2.0        2
148  149            6.2           3.4            5.4           2.3        2
149  150            5.9           3.0            5.1           1.8        2

[150 rows x 6 columns]

print(df)

In [ ]:
enc=preprocessing.OneHotEncoder()
# Label encoding converts the data in machine-readable form, but it assigns
# a unique number(starting from 0) to each class of data. This may lead to the
# generation of priority issues in the data sets


# Creates separate binary columns for each category.

In [ ]:
new_df=df.drop(columns=['Species'])

In [ ]:
enc_df=pd.DataFrame(enc.fit_transform(df[['Species']]).toarray())

In [ ]:
df_encode=new_df.join(enc_df)

In [ ]:
df_encode

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,species,0,1,2
0,1,5.1,3.5,1.0,0.2,0,1.0,0.0,0.0
1,2,4.9,3.0,1.0,0.2,0,1.0,0.0,0.0
2,3,4.7,3.2,1.0,0.2,0,1.0,0.0,0.0
3,4,4.6,3.1,1.0,0.2,0,1.0,0.0,0.0
4,5,5.0,3.6,1.0,0.2,0,1.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...
145,146,6.7,3.0,5.0,2.3,2,0.0,0.0,1.0
146,147,6.3,2.5,5.0,1.9,2,0.0,0.0,1.0
147,148,6.5,3.0,5.0,2.0,2,0.0,0.0,1.0
148,149,6.2,3.4,5.0,2.3,2,0.0,0.0,1.0
149,150,5.9,3.0,5.0,1.8,2,0.0,0.0,1.0