In [1]:
import pandas as pd
from sklearn import preprocessing

In [2]:
iris = pd.read_csv("iris.csv")

In [3]:
df = pd.DataFrame(iris,columns=["SepalLengthCm","SepalWidthCm","PetalLengthCm","PetalWidthCm"])

In [4]:
df

     SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
0              5.1           3.5            1.4           0.2
1              4.9           3.0            1.4           0.2
2              4.7           3.2            1.3           0.2
3              4.6           3.1            1.5           0.2
4              5.0           3.6            1.4           0.2
..             ...           ...            ...           ...
145            6.7           3.0            5.2           2.3
146            6.3           2.5            5.0           1.9
147            6.5           3.0            5.2           2.0
148            6.2           3.4            5.4           2.3
149            5.9           3.0            5.1           1.8

[150 rows x 4 columns]

In [5]:
x=df[df.columns].values.astype(float)

In [6]:
min_max_scalar=preprocessing.MinMaxScaler()

In [7]:
x_scaled = min_max_scalar.fit_transform(x)

In [8]:
df_normalized = pd.DataFrame(x_scaled)

In [9]:
df_normalized

            0         1         2         3
0    0.222222  0.625000  0.067797  0.041667
1    0.166667  0.416667  0.067797  0.041667
2    0.111111  0.500000  0.050847  0.041667
3    0.083333  0.458333  0.084746  0.041667
4    0.194444  0.666667  0.067797  0.041667
..        ...       ...       ...       ...
145  0.666667  0.416667  0.711864  0.916667
146  0.555556  0.208333  0.677966  0.750000
147  0.611111  0.416667  0.711864  0.791667
148  0.527778  0.583333  0.745763  0.916667
149  0.444444  0.416667  0.694915  0.708333

[150 rows x 4 columns]

In [10]:
df['Species']=iris['Species']

In [11]:
df['Species'].unique()

<StringArray>
['Iris-setosa', 'Iris-versicolor', 'Iris-virginica']
Length: 3, dtype: str

In [12]:
label_encoder=preprocessing.LabelEncoder()

In [13]:
df['Species']=label_encoder.fit_transform(df['Species'])

In [14]:
df['Species'].unique()

array([0, 1, 2])

In [15]:
df['Species'].dtype

dtype('int64')

In [16]:
df

     SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  Species
0              5.1           3.5            1.4           0.2        0
1              4.9           3.0            1.4           0.2        0
2              4.7           3.2            1.3           0.2        0
3              4.6           3.1            1.5           0.2        0
4              5.0           3.6            1.4           0.2        0
..             ...           ...            ...           ...      ...
145            6.7           3.0            5.2           2.3        2
146            6.3           2.5            5.0           1.9        2
147            6.5           3.0            5.2           2.0        2
148            6.2           3.4            5.4           2.3        2
149            5.9           3.0            5.1           1.8        2

[150 rows x 5 columns]

In [17]:
features_df=df.drop(columns=['Species'])

In [18]:
enc = preprocessing.OneHotEncoder()

In [19]:
enc_df=pd.DataFrame(enc.fit_transform(df[['Species']]).toarray())

In [20]:
df_encode = features_df.join(enc_df)

In [21]:
df_encode

     SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm    0    1    2
0              5.1           3.5            1.4           0.2  1.0  0.0  0.0
1              4.9           3.0            1.4           0.2  1.0  0.0  0.0
2              4.7           3.2            1.3           0.2  1.0  0.0  0.0
3              4.6           3.1            1.5           0.2  1.0  0.0  0.0
4              5.0           3.6            1.4           0.2  1.0  0.0  0.0
..             ...           ...            ...           ...  ...  ...  ...
145            6.7           3.0            5.2           2.3  0.0  0.0  1.0
146            6.3           2.5            5.0           1.9  0.0  0.0  1.0
147            6.5           3.0            5.2           2.0  0.0  0.0  1.0
148            6.2           3.4            5.4           2.3  0.0  0.0  1.0
149            5.9           3.0            5.1           1.8  0.0  0.0  1.0

[150 rows x 7 columns]

In [22]:
df_encode.rename(columns={0:'Iris-Setosa',1:'Iris-Versicolar',2:'Iris-Verginica'},inplace=True)

In [23]:
df_encode

,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Iris-Setosa,Iris-Versicolar,Iris-Verginica
0,5.1,3.5,1.4,0.2,1.0,0.0,0.0
1,4.9,3.0,1.4,0.2,1.0,0.0,0.0
2,4.7,3.2,1.3,0.2,1.0,0.0,0.0
3,4.6,3.1,1.5,0.2,1.0,0.0,0.0
4,5.0,3.6,1.4,0.2,1.0,0.0,0.0
...,...,...,...,...,...,...,...
145,6.7,3.0,5.2,2.3,0.0,0.0,1.0
146,6.3,2.5,5.0,1.9,0.0,0.0,1.0
147,6.5,3.0,5.2,2.0,0.0,0.0,1.0
148,6.2,3.4,5.4,2.3,0.0,0.0,1.0
149,5.9,3.0,5.1,1.8,0.0,0.0,1.0

In [24]:
one_hot_df = pd.get_dummies(df,prefix="Species",columns=['Species'],drop_first=False)

In [25]:
one_hot_df

,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species_0,Species_1,Species_2
0,5.1,3.5,1.4,0.2,True,False,False
1,4.9,3.0,1.4,0.2,True,False,False
2,4.7,3.2,1.3,0.2,True,False,False
3,4.6,3.1,1.5,0.2,True,False,False
4,5.0,3.6,1.4,0.2,True,False,False
...,...,...,...,...,...,...,...
145,6.7,3.0,5.2,2.3,False,False,True
146,6.3,2.5,5.0,1.9,False,False,True
147,6.5,3.0,5.2,2.0,False,False,True
148,6.2,3.4,5.4,2.3,False,False,True
149,5.9,3.0,5.1,1.8,False,False,True

In [26]:
col = ['Species_0','Species_1', 'Species_2']
one_hot_df[col] = one_hot_df[col].astype(int)

In [27]:
one_hot_df

,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species_0,Species_1,Species_2
0,5.1,3.5,1.4,0.2,1,0,0
1,4.9,3.0,1.4,0.2,1,0,0
2,4.7,3.2,1.3,0.2,1,0,0
3,4.6,3.1,1.5,0.2,1,0,0
4,5.0,3.6,1.4,0.2,1,0,0
...,...,...,...,...,...,...,...
145,6.7,3.0,5.2,2.3,0,0,1
146,6.3,2.5,5.0,1.9,0,0,1
147,6.5,3.0,5.2,2.0,0,0,1
148,6.2,3.4,5.4,2.3,0,0,1
149,5.9,3.0,5.1,1.8,0,0,1